apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-deployment
spec:
  selector:
    matchLabels:
      app: internal
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
      - name: internal
        image: deepakdinio/git_devop_internal1:2
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
